### ISSUE TITLE
Appveyor builds and webhooks

### ISSUE THREAD

**Issue by maelle** [ropensci/rrricanes#116]
:wave: @timtrice !

I'm currently looking for Appveyor broken hooks over ropensci repos and I see you have [3 Appveyor hooks](https://github.com/ropensci/rrricanes/settings/hooks). Builds are under your Appveyor account which is fine (we're on the edge about no longer recommending transfering Appveyor builds to ropensci Appveyor account because it seems to lead to more issues)

Normally there should be only webhook but transfer of the repo can create several ones. Two of them have failed deliveries, one doesn't, but it seems there was no build for your latest commit https://ci.appveyor.com/project/timtrice/rrricanes-g4dos so it wouldn't be enough to just delete the broken ones.

I'd advise you to contact Appveyor support team at team@appveyor.com and ask them which hook(s) to delete and to reactivate one of them if needed. They'll probably need this info

* Hook 1 https://github.com/ropensci/rrricanes/settings/hooks/15375471
Latest delivery: X-GitHub-Delivery: 24579f56-3209-11e8-8e0f-74b4ce1ae222 on 2018-03-27 23:52:28

* Hook 2 https://github.com/ropensci/rrricanes/settings/hooks/14031491
Latest delivery: X-GitHub-Delivery: 24579f56-3209-11e8-8e0f-74b4ce1ae222 on 2018-03-27 23:52:28

* Hook 3 https://github.com/ropensci/rrricanes/settings/hooks/13620673
Latest delivery: X-GitHub-Delivery: 24579f56-3209-11e8-8e0f-74b4ce1ae222 on 2018-03-27 23:52:28

They should be able to help you. Thanks!

**Comment by maelle** [comment]
Maybe try that first (email received this night from Appveyor)

* New commit and push (the "account" was blocked, unclear to me whether they mean Appveyor or GitHub...)

* If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 *   If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account.

**Comment by timtrice** [comment]
@maelle,

Yesterday, I deleted the hooks and readded. I'm unsure exactly what is going on with this as I'm not familiar with Appveyor at all.

**Comment by maelle** [comment]
Thanks! The hook now looks fine but the latest build I see at https://ci.appveyor.com/project/timtrice/rrricanes-g4dos is not for the latest commit... Maybe try pushing anything to the repo to trigger a new build?

**Comment by timtrice** [comment]
Ok, I believe we're on the same page now. I did make some changes but apparently the push went to my old appveyor webhook (which is running). I grabbed the webhook from the appveyor link you sent and switched them out, did a dummy push and now , I guess the ropensci appveyor is running. 

Unless I'm missing something, Appveyor seems terribly confusing in this aspect.  Do you suppose I may be having the same issues with `rrricanesdata`?

**Comment by maelle** [comment]
> Unless I'm missing something, Appveyor seems terribly confusing in this aspect. 

We're _really_ on the same page 😉 I like how Travis just works.

No `rrricanesdata` is fine, it wasn't in my list and I've just had a look at the repo and Appveyor page, all good.

I think I can close this now, thanks a ton for your patience!
