### ISSUE TITLE
Your twitter DatSignal

### ISSUE THREAD

**Issue by hrbrmstr** [ropensci/rrricanes#62]
I'm technically taking a sabbatical from Twitter but an RSS feed of the `#rstats` hashtag doesn't technically violate the sabbatical conditions :-)

```
library(httr)
library(rvest)
library(tidyverse)

pb <- progress_estimated(8)
map(2009L:2016L, ~{
  
  pb$tick()$print()
  
  Sys.sleep(3L)
  
  POST("http://www.nhc.noaa.gov/gis/archive_wsp.php",
       body = list(year = .x), encode = "form") -> res
  
  pg <- content(res, as="parsed", encoding="UTF-8")
  
  html_nodes(pg, "a[href*='kmz']") %>% 
    html_attr("href")
  
}) %>% 
  flatten_chr() -> kmzs
```

But, the URLs are in the rds below. You just need to d/l & extract them all.

[kmds.rds.zip](https://github.com/timtrice/rrricanes/files/1039972/kmds.rds.zip)

**Comment by timtrice** [comment]
Thank you very much for this! That looks stupid simple. I don't have my old code; I had to restart my session. Seems I was on the right track but no idea where I went off now.

What I'm trying to do; there's two different products for each date and then additionally by resolution. As you may have noticed it can take a while, at least on my system. So I want to give the user the option to drill down to a certain level of detail. 

So this will help out a lot, thank you!

**Comment by timtrice** [comment]
Is your name Bob Pyaic? I'd like to add you as a contributor to the project if you don't mind.

**Comment by timtrice** [comment]
Ignore that, I found it on another project.
