### ISSUE TITLE
change `.cols` arg for `dplyr` calls

### ISSUE THREAD

**Issue by mpadge** [ropensci/rrricanes#74]
### Error Message

```
`.cols` has been renamed and is deprecated, please use `.vars`
```

### Reproducible Example

You might have to do this with a fresh repo clone - after turning off `.Rprofile`
```
devtools::load_all (".", export_all = FALSE)
testthat::test_package ("rrricanes")
```
The error message prevents the progress bar from working, and fills the screen up with junk. See this [comment in `dplyr`](https://github.com/tidyverse/dplyr/blob/master/R/colwise-mutate.R#L17-L18). You probably just need to update `fstadv.R`.

**Comment by timtrice** [comment]
Mark, is this preventing you from the timeout fix?

**Comment by mpadge** [comment]
nup, [done!](https://github.com/timtrice/rrricanes/pull/75)

**Comment by timtrice** [comment]
This change was made at some point between dplyr 0.5.0 and dplyr 0.7.0. I'm unable to find any documentation that clarifies which. 

Either way, will branch off the latest passing release and test against dplyr 0.7.0 to ensure no other functionality is broken in the process. Assuming all goes well should be part of the 0.2.0 release.

**Comment by timtrice** [comment]
Commited patch to accomodate versions of dplyr 0.5.0 and dplyr >= 0.5.0. 

Support for dplyr 0.5.0 will be removed in future releases.

All tests and checks pass.
